{% set name = "jupyter_sphinx" %}
{% set version = "0.5.3" %}
{% set sha256 = "2e23699a3a1cf5db31b10981da5aa32606ee730f6b73a844d1e76d800756af56" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: true  # [py<36]
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python
  run:
    - python
    - sphinx >=2.0
    - ipywidgets >=7.0.0
    - IPython
    - nbconvert >=5.5
    - nbformat

test:
  imports:
    - jupyter_sphinx

about:
  home: https://github.com/jupyter/jupyter-sphinx
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Include Jupyter outputs in Sphinx documentation.
  dev_url: https://github.com/jupyter/jupyter-sphinx

extra:
  recipe-maintainers:
    - SylvainCorlay
    - akhmerov
    - jbweston
    - 12rambau
