{% set name = "jupyter_sphinx" %}
{% set version = "0.2.3" %}
{% set sha256 = "aaf7c9e0b6172432fca727b908bc296cc575159d3f948332886ba850357f66e7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1
  skip: true  # [py<35]
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - pip
    - python
  run:
    - python
    - sphinx >=1.8
    - ipywidgets >=7.0.0
    - IPython
    - nbconvert >=5.5
    - nbformat

test:
  imports:
    - jupyter_sphinx

about:
  home: https://github.com/jupyter/jupyter-sphinx
  license: BSD 3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'Include Jupyter outputs in Sphinx documentation.'
  dev_url: https://github.com/jupyter/jupyter-sphinx

extra:
  recipe-maintainers:
    - SylvainCorlay
    - akhmerov
    - jbweston
